### ISSUE TITLE
Re-enable support for Debian Bookworm and Kali Linux

### ISSUE THREAD

**Issue by jsf9k** [cisagov/ansible-role-freeipa-client#51]
# 💡 Summary #

Re-enable support for Debian Bookworm and Kali Linux once a `freeipa-client` package becomes available for those platforms.

## Motivation and context ##

We should support any platforms that we can.

**Comment by mcdonnnj** [comment]
Per https://tracker.debian.org/news/1354261/freeipa-498-1-migrated-to-testing/ and https://packages.debian.org/bookworm/freeipa-client I believe we may be back in business.

**Comment by jsf9k** [comment]
Blocked until #54 is approved and merged.

**Comment by jsf9k** [comment]
Now unblocked, as #54 has been approved and merged.
